#!/bin/bash
# Author: Jesse Chenhalls
# Created Date: 20230731
# will take a series of .zip files and unzip them each to their own directory. 


dirname=''
for i in $(ls) 
	do dirname=$(echo $i | awk -F '.zip' '{print $1}') 
	echo $dirname 
	mkdir $dirname 
  newdir="${dirname}/"
  unzip $i -d $newdir;
done
dirname=''
newdir=''
